Merge ironic and ironic-inspector repositories
metal3-io/ironic-image pull request #252
Opened 2021-04-12 10:09 UTC by elfosardo

This change moves Dockerfile, configuration and scripts from the
ironic-inspector container image repository to the ironic one.

This approach provides two separate Dockerfiles in the same repository,
one for ironic and one for ironic-inspector, that share part of the
logic needed to build the images.
The scripts and configurations are kept separated for the time being as
some of them conflict with each other (e.g. runhttpd).

The original Dockerfile is kept until we make the necessary changes to
the CI.

2021-04-12 10:11 UTC, elfosardo commented
/assign @maelk @dtantsur @hardys

2021-04-12 12:43 UTC, elfosardo commented
/test-integration

2021-04-12 13:37 UTC, dtantsur requested changes
I'd prefer we don't go down this patch. This defeats one of the upsides of merging images: sharing most of the Python base and the httpd service.

2021-04-16 10:51 UTC, elfosardo commented
consensus is on single dockerfile, so closing this

2021-04-16 10:51 UTC, closed without merging