Update tripleo_repos location
metal3-io/ironic-image pull request #288
Opened 2021-07-26 01:16 UTC by adetalhouet

The upstream openstack tripleo team decided to move the `tripleo_repos` folder under `plugins/module_utils/` https://github.com/openstack/tripleo-repos/commit/77dc5794ac880abc57927af08e70e99d2a972f84
Due to this, when building the ironic container, we end us with a `404 Not Found` error.
Updating the script as per as the new upstream repo structure.

2021-07-26 13:35 UTC, elfosardo commented
/approve

2021-07-27 09:52 UTC, elfosardo commented
/test-integration

2021-07-27 13:01 UTC, elfosardo requested changes
we also need to change the Dockerfile of the vbmc image resources/vbmc/Dockerfile

2021-07-27 13:57 UTC, adetalhouet commented
> we also need to change the Dockerfile of the vbmc image resources/vbmc/Dockerfile
Ok, done. Thanks for reviewing.

2021-07-27 13:59 UTC, elfosardo requested changes

2021-07-27 13:59 UTC, elfosardo commented on resources/vbmc/Dockerfile
> +     curl https://raw.githubusercontent.com/openstack/tripleo-repos/master/plugins/module_utils/tripleo_repos/main.py | python3 | python3 - -b master current-tripleo --no-stream && \
remove the new python 3 command

2021-07-27 14:01 UTC, adetalhouet commented on resources/vbmc/Dockerfile
> +     curl https://raw.githubusercontent.com/openstack/tripleo-repos/master/plugins/module_utils/tripleo_repos/main.py | python3 | python3 - -b master current-tripleo --no-stream && \
my bad. fixed

2021-07-27 14:32 UTC, elfosardo commented
/test-integration

2021-07-27 14:33 UTC, elfosardo commented
/lgtm

2021-07-27 15:05 UTC, elfosardo commented
/test-integration

2021-07-27 21:03 UTC, furkatgofurov7 commented
/test-integration

2021-07-28 07:34 UTC, dtantsur commented
/approve

2021-07-28 07:35 UTC, merged