upgrading setuptools and pip in patch-image
metal3-io/ironic-image pull request #422
Opened 2023-06-14 10:32 UTC by adilGhaffarDev

To fix ci.
Ref: https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_main_fullstack_building/191/consoleFull

2023-06-14 10:44 UTC, adilGhaffarDev commented
/test-ubuntu-integration-main

2023-06-14 12:01 UTC, elfosardo requested changes

2023-06-14 12:01 UTC, elfosardo commented on patch-image.sh
> +    pip3 install -U setuptools
same here
if we need setuptools, let's include it in dnf command in L7

2023-06-14 12:01 UTC, elfosardo commented on patch-image.sh
> +dnf remove -y python3-pip git-core setuptools
youre removing setuptools with dns when it was installed with pip?

2023-06-14 12:36 UTC, adilGhaffarDev commented
/hold

2023-06-14 12:45 UTC, adilGhaffarDev commented on patch-image.sh
> +    /usr/bin/python3 -m pip install --upgrade pip
We don't need to upgrade pip, I will resolve the problem by upgrading the setuptools version. It seems that the error that we are getting in our in patch-image script is caused by a change in the setuptools version. Previously, when rpm was the default package manager, we were using python3-setuptools-57.4.0. However, in recent CI runs, we are now getting python3-setuptools-53.0.0. I'm unsure why this version is changing. I am running local tests where I solely upgrade the setuptools for the patch image script, I will push those changes once test passed. Holding this PR

2023-06-14 13:03 UTC, elfosardo commented on patch-image.sh
> +    /usr/bin/python3 -m pip install --upgrade pip
that's odd, the same setuptools is used during installation in https://github.com/metal3-io/ironic-image/blob/main/prepare-image.sh#L31
it's then removed, but you can reinstall it using dnf

2023-06-22 06:33 UTC, adilGhaffarDev commented
fixed the issue by removing patching. https://github.com/Nordix/metal3-dev-tools/pull/681 
I will add followup pr to remove patch script too.

2023-06-22 06:35 UTC, closed without merging