Add tag trigger to images building wf
metal3-io/ironic-image pull request #456
Opened 2023-12-01 10:33 UTC by mquhuy

2023-12-01 10:36 UTC, mquhuy commented
/hold

2024-01-08 08:23 UTC, tuminoid commented
Please add PR description. Otherwise this is LGTM and up to date?

2024-01-09 14:22 UTC, elfosardo commented
jsut waiting for PR description to approve it

2024-01-10 08:08 UTC, mquhuy commented
/unhold

2024-01-10 08:12 UTC, mquhuy commented
Description added. The PR is up to date.

2024-01-10 08:14 UTC, tuminoid commented
> Description added. The PR is up to date.

Add the :seedling: in the title. It is now required in ironic-image.

2024-01-10 08:14 UTC, tuminoid commented
/retitle 🌱 Add tag trigger to images building wf

2024-01-10 08:16 UTC, tuminoid requested changes

2024-01-10 08:16 UTC, tuminoid commented on .github/workflows/build-images-action.yml
> +      - 'capm3-v*'
We're not tagging it capm3-* anymore, but using the normal 'vx.y.z`

2024-01-11 06:44 UTC, tuminoid approved these changes
/lgtm

2024-01-11 06:44 UTC, tuminoid commented
/override test-centos-integration-main  test-ubuntu-integration-main 
Not relevant

2024-01-11 06:44 UTC, tuminoid commented
/cc @elfosardo @dtantsur 
This is good to merge, please check.

2024-01-15 08:59 UTC, tuminoid commented
@elfosardo @dtantsur
Can we get an approve here?

2024-01-15 10:29 UTC, elfosardo commented
/approve

2024-01-15 10:29 UTC, merged

2024-01-17 14:06 UTC, tuminoid commented
Disabled image builds in Quay for Ironic, VBMC and sushy-tools images. Images are now build by this workflow+Jenkins.