:seedling: Use pynotify instead of inotify-tools
metal3-io/ironic-image pull request #607
Opened 2024-12-23 14:36 UTC by elfosardo

The inotify-tools last release is from september 2023
and last update in the repo is 7 months old (May 2024).
The inotify-tools package is not present in the EPEL10 repo
anymore while python3-inotify is in a native repository.
This change allows us to remove dependency from EPEL entirely.

Signed-off-by: Riccardo Pittau <elfosardo@gmail.com>

Closes https://github.com/metal3-io/ironic-image/issues/605

2024-12-23 14:37 UTC, elfosardo commented
/test metal3-centos-e2e-integration-test-main metal3-ubuntu-e2e-integration-test-main

2024-12-24 15:05 UTC, dtantsur requested changes
The change looks good. There are a few other places where inotify is used, could you update them as well?

Also note that pyinotify is even more ancient: its last release was in 2015. I guess it still works well if it's included in the repos.

2025-01-07 11:28 UTC, dtantsur approved these changes

2025-01-07 13:01 UTC, elfosardo commented
/test metal3-centos-e2e-integration-test-main metal3-ubuntu-e2e-integration-test-main

2025-01-07 13:23 UTC, tuminoid commented
Good thing about Python inotify packages is that they all just implement ctypes wrappers for libc's functionality and do not try to reinvent the wheel. Hence most of the fixes, barring language incompatibilities down the road, are coming from OS packages, and it is not as relevant to have the python package updating all the time.

2025-01-07 14:03 UTC, merged